In [3]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int32

Array:
[1 2 3]
Dimension: 1
Data type: int32

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int32



In [11]:
# 2 Array Dimension: Shape and Reshape of Array :
import numpy as np
array_0d = np.array(5)
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])
# print arrays with shapes
for i, arr in enumerate([array_0d,array_1d,array_2d,array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")


0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
Shape: (1, 4, 2)



In [25]:
# Reshaping Array
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
reshaped_array = array.reshape(3,2)
print("Original Shape: ",array.shape,"\nReshaped Shape:",reshaped_array.shape)
print(array )
print(reshaped_array)

Original Shape (2, 3) 
Reshaped Shape: (3, 2)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [29]:
# Sample code from slide -17 Reshaping an Array
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
reshaped_array = array.reshape(3,2)
print("Original Shape:",array.shape,"\nReshaped Shape:",reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [41]:
# Array Creation
# Arrays with 
# slide 18
import numpy as np
a = np.arange(1,10)
print(a)
x = range(1,10)
print(x)
print(list(x))
x= np.arange(10.4)
print(x)
x = np.arange(0.5,10.4,0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [43]:
# Sample Code from Slide - 19 - Arrays with evenly Spaced values - linspace.
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1,10))
# 7 values between 1 and 10 
print(np.linspace(1,10,7))
# excludeing the endpoint
print(np.linspace(1,10,7,endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [45]:
# Sample Code form slide - 20 - Initializing an Array.
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2,3))
zeros_array = np.zeros((3,2))
empty_array = np.empty((2,3))
identity_matrix = np.eye(3)
print(ones_array,zeros_array,empty_array,identity_matrix,sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [2.33644129e-307 1.69113762e-306 1.33511562e-306]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
# Sample Code form slide - 21 - Converting list to array using np.array.
import numpy as np
array_from_list = np.array([1,2,3]) # [1 2 3]
array_from_tuple = np.array((4,5,6))
array_from_nested_list = np.array([[1,2,3],[4,5,6]])
print(array_from_list,array_from_tuple,array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [49]:
# Sample Code form slide - 22 - From shape of an existing array.
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape)
print(arr,zeros,ones,empty,sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [2.33644129e-307 1.69113762e-306 1.33511562e-306]]


In [53]:
# Sample Code form slide - 23 - Manipulatiing existing array.
import numpy as np
array = np.array([1,2,3])
new_array = array *2
copies_array = np.copy(array)
sliced_array = array[1:2]
print(array,new_array,copies_array,sliced_array,sep='\n')


[1 2 3]
[2 4 6]
[1 2 3]
[2]


In [57]:
# Warming up exercise:Basic Vector and Matrix Operation with Numpy
# qn 1
import numpy as np
empty_array = np.empty((2,2))
print(empty_array)

[[2.12199579e-314 1.24773353e-311]
 [2.94463125e-321 6.95314361e-310]]


In [61]:
# initialize an all one array with size 4*2
# qn 2
import numpy as np
one_array = np.ones((4,2))
print(one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [63]:
# Return a new array of given shape and type, filled with fill value.{Hint: np.full}
# qn3
import numpy as np
array = np.full((3,3),7)
print(array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [65]:
# Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
# qn4
import numpy as np
original_array = np.array([[1,2,3],[4,5,6]])
zeros_array = np.zeros_like(original_array)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [67]:
# Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
# qn5
import numpy as np
original_array = np.array([[3,4,5],[6,7,8]])
ones_array = np.ones_like(original_array)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [69]:
# For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
# qn6
import numpy as np
new_list = [1,2,3,4]
to_array = np.array(new_list)
print(to_array)

[1 2 3 4]


In [71]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
# qn 1
import numpy as np
a = np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [91]:
# qn2
import numpy as np
array = np.arange(9)
matrix = array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [95]:
# qn3
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [105]:
# qn4
import numpy as np
array = np.random.random(30)
mean_matrix = array.mean()
print(mean_matrix)

0.5605313139312033


In [117]:
# qn5
import numpy as np 
array = np.random.random(100)
reshape_array = array.reshape(10,10)
print(reshape_array)
maximum_value = reshape_array.max()
minimum_value = reshape_array.min()
print(maximum_value)
print(minimum_value)

[[0.17427105 0.60228878 0.74888207 0.71277313 0.49292527 0.87055992
  0.63177757 0.58610395 0.38431468 0.95749843]
 [0.33623303 0.9620675  0.68443781 0.47490731 0.29503425 0.04095913
  0.42420855 0.03962821 0.02591018 0.64709942]
 [0.65673031 0.22902483 0.79117773 0.66477678 0.46559624 0.44334924
  0.89893975 0.36673539 0.31930371 0.87929386]
 [0.20403056 0.70888822 0.15304306 0.10476233 0.38064333 0.07080773
  0.45399784 0.96182653 0.92670607 0.099623  ]
 [0.09562349 0.27508267 0.85104519 0.98075073 0.94525661 0.92812036
  0.60074782 0.76747831 0.53458964 0.87046681]
 [0.37322697 0.84095669 0.60352934 0.6862609  0.91946377 0.7981548
  0.17625113 0.68685442 0.15185466 0.42536466]
 [0.73234418 0.60802772 0.2915939  0.03688959 0.13452716 0.97099422
  0.22074881 0.12637544 0.37099991 0.95595328]
 [0.30704553 0.86527297 0.55722904 0.54240829 0.98506502 0.10388934
  0.54432339 0.2048287  0.68887173 0.04986812]
 [0.0379137  0.58694113 0.31889562 0.59981802 0.73582127 0.33570434
  0.48014139 

In [121]:
# qn6
import numpy as np
zeros_array = np.zeros(10)
zeros_array[5] = 1
print(zeros_array)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [127]:
# qn7
arr = [1,2,0,0,4,0]
revers_array = np.flip(arr)
print(revers_array)

[0 4 0 0 2 1]


In [131]:
# qn8
import numpy as np
rows ,cols = 6,6
array = np.zeros((rows,cols),dtype=int)
print(array)
# 1st row
array[0,:] =1
print(array)
# last row
array[-1,:]=1
print(array)
# 1st column
array[:,0]=1
print(array)
# last column
array[:,-1]=1
print(array)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1 1 1 1 1 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1 1 1 1 1 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [135]:
import  numpy as np 
rows , cols = 8,8
checkerboard = np.zeros((rows,cols),dtype=int)
print(checkerboard)
checkerboard[1::2, ::2] = 1 #Odd rows ,even columns
print(checkerboard)
checkerboard[::2, 1::2] = 1  # Even rows, odd columns
print(checkerboard)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# matrix multiplications
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using np.dot
result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot) # Output shape: (2, 2)

In [139]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
# Output: Inverse: [[-2. 1. ], [ 1.5 -0.5]]
print("Determinant:", np.linalg.det(A))
# Output: Determinant: -2.0
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
# Output: Frobenius Norm: 5.4772
print("2-Norm (Euclidean):", np.linalg.norm(A))
# Outptut: 2-Norm(Euclidean): 5.4772
print("Solution x:", np.linalg.solve(A,B))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


In [143]:
# qn1 
A = np.array([[3,4],[7,4]])
A_inverse = np.linalg.inv(A)
I = np.dot(A,A_inverse)
print(I)

[[1. 0.]
 [0. 1.]]


In [155]:
# qn2
import numpy as np
A = np.array([[3,4],[7,4]])
B = np.array([[5,3],[2,1]])
A_B = np.dot(A,B)
B_A = np.dot(B,A)
print(A_B)
print(B_A)


[[23 13]
 [43 25]]
[[36 32]
 [13 12]]


In [161]:
# qn3
import numpy as np
A = np.array([[3,4],[7,4]])
B = np.array([[5,3],[2,1]])
AB = np.dot(A,B)
TA = A.transpose()
TB = B.transpose()
BTAT = np.dot(TB,TA)
ABT = AB.transpose()
print("(AB)^T  = ",ABT )
print("B^TA^T = ",BTAT)

(AB)^T  =  [[23 43]
 [13 25]]
B^TA^T =  [[23 43]
 [13 25]]


In [171]:
import numpy as np
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([[-1],[-3],[9]])
IA = np.linalg.inv(A)
X = np.dot(IA,B)
print("X=",X[0],"Y=" ,X[1],"Z=", X[2])

X= [2.] Y= [1.] Z= [-2.]


In [177]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
add = np.add(x,y)
print(add)
subtract = np.subtract(x,y)
print(subtract)
multiply = np.dot(x,y)
print(multiply)
x2 = np.power(x,2)
print(x2)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[19 22]
 [50 58]]
[[ 1  4]
 [ 9 25]]
